### ISSUE TITLE
Unable to pick photos from Gallery on Android

### ISSUE THREAD

**Issue by joeykang** [dimonovdd/Xamarin.MediaGallery#93] opened 2022-02-08 21:12 UTC
### Description
Unable to pick photos from Gallery(Photos app) on Android. But picking photos from other places like Download works correctly.
### Actual Behavior
If I pick a photo from Gallery(Photos app) it returns empty result, not crash.
### Expected behavior
It should return selected photo as a result.
### Steps to reproduce the behavior
1. Call PickAsync()
2. call results?.Files?.ToArray();
3. 

### Screenshots or Videos
<img width="975" alt="image" src="https://user-images.githubusercontent.com/7174560/153076284-d757e520-773a-4f90-b967-b54b08ff48d1.png">

### Configuration
 - Device: Google Pixel 3a
 - OS Version: Android 30
 - Plugin Version: 2.1.1
 - Framework: Xamarin or MAUI: Xamarin

**Comment by dimonovdd** [comment] 2022-02-09 09:08
Hi
1) Have you tested this on a real device or simulator?
2) Can you provide a sample?

**Comment by joeykang** [comment] 2022-02-09 14:27
> Hi
> 
> 1. Have you tested this on a real device or simulator?
> 2. Can you provide a sample?

1. Yes I tested it on real device, Google Pixel 3a(API 30).
2. This is the snippet to get photo from the device. if clause did not get caught when selecting a photo from Photos(app). As you see in the screenshot, 'results' and 'capturedPhotos' variables were not null. But it gets photos correctly from other places like 'Download' folder.
````
                    var results = await MediaGallery.PickAsync(1, MediaFileType.Image); // Allow only one selection
                    capturedPhotos = results?.Files?.ToArray();

                    if (capturedPhotos != null && capturedPhotos.Count() == 1)
                    {
                        filePath = await LoadPhotoAsync(capturedPhotos[0]);
                        capturedPhotos[0].Dispose();
                    }
````

**Comment by dimonovdd** [comment] 2022-02-10 18:55
I can't reproduce this issue. Can you send me a small sample project?

**Comment by joeykang** [comment] 2022-02-10 22:16
> I can't reproduce this issue. Can you send me a small sample project?

I tested it again with a small sample app and this issue was not happening. I compared related codes between the sample app and my app but I could not find any significant differences. Only thing I observed was OnActivityResult() got called with resultCode 'cancelled' in my app. Whereas, for the sample, OnActivityResult() returns with resultCode 'ok'. This means, in my app, picking a photo from Photos makes OnActivityResult() with failed Result. Any ideas?
````
protected override void OnActivityResult(int requestCode, Result resultCode, Intent intent)
{
    if (NativeMedia.Platform.CheckCanProcessResult(requestCode, resultCode, intent))
        NativeMedia.Platform.OnActivityResult(requestCode, resultCode, intent);

    base.OnActivityResult(requestCode, resultCode, intent);
}
````

**Comment by dimonovdd** [comment] 2022-02-10 22:41
Maybe there are differences in project settings? AndroidManifest, csproj and etc.

**Comment by smalgin** [comment] 2022-02-14 00:11
I found some time & made a sample!

Very interesting bug:
Pick from local files works fine, but when I try to pick from Google Drive, everything is gray.
Xamarin.Essentials image picker works without any extra steps.

Repro steps:
1) VS 2019

2) provided project

3) Set up Emulator as shown (Essentially Pixel/R/30 with 4GB RAM and forced GPU)
![image](https://user-images.githubusercontent.com/8367800/153781469-b4615d2e-fcda-4080-bf21-9780037ff6fb.png)

4)  set up Google account there & make sure you have some images in your Google Drive app

5) Try to pick image from Drive. All is gray, you can only pick 'cancel'.

NOTE: Picking from Google Photos works!

[MediaGallery.zip](https://github.com/dimonovdd/Xamarin.MediaGallery/files/8056969/MediaGallery.zip)

**Comment by smalgin** [comment] 2022-02-14 00:12
Good user, I deserve a cookie! :)

**Comment by dimonovdd** [comment] 2022-02-14 06:13
> Try to pick image from Drive. All is gray, you can only pick 'cancel'.

https://github.com/dimonovdd/Xamarin.MediaGallery/issues/87#issuecomment-1006673216

**Comment by dimonovdd** [comment] 2022-02-14 06:16
I have closed this issue, Discussions related to Google Drive will be discussed in a separate issue: #87

**Comment by joeykang** [comment] 2022-02-14 19:01
> Maybe there are differences in project settings? AndroidManifest, csproj and etc.

Tried changes for AndroidManifest.xml, csproj and AssemblyInfo.cs but no luck. Frustrating.

**Comment by dimonovdd** [comment] 2022-02-15 23:07
Maybe can you give me access to your project?

**Comment by joeykang** [comment] 2022-02-16 14:43
> Maybe can you give me access to your project?

Sorry it's not open project.

**Comment by matthewyoungias** [comment] 2022-11-25 16:40
Same issue when moving to API 30 from 29. It worked before doing this.

**Comment by dimonovdd** [comment] 2022-11-25 18:06
@matthewyoungias Can you give a sample project?

**Comment by dimonovdd** [comment] 2022-11-28 20:55
need more information

**Closed by dimonovdd** 2022-11-28 20:55 UTC
Labels: bug
