### ISSUE TITLE
Camera app doesn't open on CapturePhotoAsync

### ISSUE THREAD

**Issue by smalgin** [dimonovdd/Xamarin.MediaGallery#88] opened 2021-12-21 03:58 UTC
### Description

Camera app doesn't open on CapturePhotoAsync

### Expected behavior

Should open the camera app. Xamarin.Essentials media picker works.

### Code snippet

if (MediaGallery.CheckCapturePhotoSupport())
                return;

            var status = await Permissions.RequestAsync<Permissions.Camera>();

            if (status != PermissionStatus.Granted)
                return;

            using var photoFile = await MediaGallery.CapturePhotoAsync();

### Configuration
 - Device: Galaxy Tab A SM-510
 - OS Version: Android 11, OneUI 3.1
 - Plugin Version: latest

**Comment by dimonovdd** [comment] 2021-12-21 09:32
1) What value does `CheckCapturePhotoSuppor` method return?
2) Can you show your android manifest file?
3) Can you provide more information? LogCat or behavior on other devices on your app

**Comment by joeykang** [comment] 2022-02-03 19:36
I had the same issue on Android. Looks like it happens when the app was built with the target of API level 30 in AndroidManifest.xml. It was ok with API level 29.

CheckCapturePhotoSupport returns false in this issue. If I ignore CheckCapturePhotoSupport() and proceed the app will crash.

**Comment by dimonovdd** [comment] 2022-02-03 21:39
@joeykang hi. Can you send me your AndroidManifest.xml?

**Comment by joeykang** [comment] 2022-02-03 22:15
> @joeykang hi. Can you send me your AndroidManifest.xml?

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" package="com.myapp.mobile" android:installLocation="auto" android:versionName="2.1.2">
	<uses-sdk android:minSdkVersion="23" android:targetSdkVersion="30" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<application android:label="my app">
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="com.myapp.mobile.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
		</provider>
		<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="myapp_general" />
		<service android:name="com.myapp.mobile.LocalFirebaseMessagingService" android:exported="false">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT" />
			</intent-filter>
		</service>
	</application>
</manifest>

**Comment by joeykang** [comment] 2022-02-03 22:16
Here is my AndroidManifest.xml

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" package="com.myapp.mobile" android:installLocation="auto" android:versionName="2.1.2">
	<uses-sdk android:minSdkVersion="23" android:targetSdkVersion="30" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<application android:label="MyApp">
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="com.myapp.mobile.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
		</provider>
		<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="myapp_general" />
		<service android:name="com.myapp.mobile.LocalFirebaseMessagingService" android:exported="false">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT" />
			</intent-filter>
		</service>
	</application>
</manifest>

**Comment by joeykang** [comment] 2022-02-03 22:17
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" package="com.myapp.mobile" android:installLocation="auto" android:versionName="2.1.2">
	<uses-sdk android:minSdkVersion="23" android:targetSdkVersion="30" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<application android:label="MyApp">
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="com.myapp.mobile.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
		</provider>
		<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="myapp_general" />
		<service android:name="com.myapp.mobile.LocalFirebaseMessagingService" android:exported="false">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT" />
			</intent-filter>
		</service>
	</application>
</manifest>

**Comment by dimonovdd** [comment] 2022-02-04 22:55
@joeykang You should configure your AndroidManifest.xml as described in [Readme](https://github.com/dimonovdd/Xamarin.MediaGallery#android-2)

**Comment by joeykang** [comment] 2022-02-07 14:54
> @joeykang You should configure your AndroidManifest.xml as described in [Readme](https://github.com/dimonovdd/Xamarin.MediaGallery#android-2)

Comparing my AndroidManifest.xml with the one in [README](https://github.com/dimonovdd/Xamarin.MediaGallery#android-2), a setting below was missing in my AndroidManifest.xml
````
<uses-feature android:name="android.hardware.camera" android:required="true" />
````
I added it in my AndroidManifest.xml but no luck with that on Google Pixel 3a and Android 30 emulator.

**Comment by dimonovdd** [comment] 2022-02-07 16:47
@joeykang it is also mandatory
```xml
<queries>
  <intent>
    <action android:name="android.media.action.IMAGE_CAPTURE" />
  </intent>
</queries>
```

**Comment by joeykang** [comment] 2022-02-07 20:01
@dimonovdd  it worked ok with what you mentioned. There was my misunderstanding of configurations for Android. I appreciate your quick response.

> @joeykang it is also mandatory
> 
> ```
> <queries>
>   <intent>
>     <action android:name="android.media.action.IMAGE_CAPTURE" />
>   </intent>
> </queries>
> ```

**Comment by dimonovdd** [comment] 2022-02-07 20:05
@smalgin Have you tried it? Can I close the issue?
@joeykang I'm glad. Next time you should be more attentive to a little things😉

**Comment by smalgin** [comment] 2022-02-08 08:40
I'll try in a couple days. Too busy with the day's work.

**Comment by smalgin** [comment] 2022-02-13 02:05
In emulator:
Did everything as prescribed, still Google Drive won't let me pick any files. 
Tried to cap from Emulated camera - img is captured but no mediafile at the exit.
Then my Emulator froze.
Resetting Emulator to factory defaults...

**Comment by dimonovdd** [comment] 2022-02-13 08:39
Can you send me a small sample project? I would like to fix the bugs if there is one. But I can't reproduce it.

**Comment by dimonovdd** [comment] 2022-02-13 08:45
Currently 2.1.1 is the latest version of the plugin

**Comment by smalgin** [comment] 2022-02-13 10:41
I suspect that if I create empty Xamarin project w latest everything it might just work.
I'll try, but ETA is unclear, sorry - too much stuff is happening around.

**Comment by Lukata** [comment] 2022-02-22 17:47
Hello @smalgin 

I faced the same issue on iOS and the problem was that I wasn't asking for the permission to open the camera.

Something like that solve my issue:

` 
var status = await Permissions.CheckStatusAsync<Permissions.Camera>();
 if(status != PermissionStatus.Granted)
                    {
                        var request = await Permissions.RequestAsync<Permissions.Camera>();
                        if (request == PermissionStatus.Denied)
                            return null;
                    }
if (DeviceInfo.Platform == DevicePlatform.iOS)
                    {
                        IMediaFile media = await MediaGallery.CapturePhotoAsync();
                        return media;
                    }
`

**Comment by dimonovdd** [comment] 2022-02-22 18:04
@Lukata Hi. Can you provide a sample?


I think you should change the function of getting a controller:

https://github.com/dimonovdd/Xamarin.MediaGallery#ios-optional

**Comment by Lukata** [comment] 2022-02-22 18:53
Hi @dimonovdd,

I solved my issue with the code I sent in my previous message :)

I just answered to this topic because it might be related because on Android too I had this issue and the problem was that I was missing the permission request (MediaGallery doesn’t open if you don’t ask the permission, and by default the  permission is not Denied but Unknown).

best regards,

Lucas.

**Closed** 2022-04-14 20:05 UTC
Labels: bug, android, CapturePhoto
